name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: sh ./paper/repush.sh

  upload:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: upload thesis
      env: 
        LOGIN_ID: ${{ secrets.LOGIN_ID }}
        LOGIN_PASS: ${{ secrets.LOGIN_PASS }}
        FILE_TITLE: ${{ secrets.FILE_TITLE }}
      run: cd sotsuron-push && docker-compose up -d hub uploader && docker-compose logs -f uploader
